version: '3.6'
services:
  mongomotors:
    image: 'mongo'
    container_name: 'mongomotors'
    environment: 
      - MONGO_INITDB_DATABASE=crawler
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=rootteste
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_webmotors_data:/data/db
    ports:
      - 27017:27017
    expose:
      - '27017'
  mysqlmotors:
    image: mysql:8.0
    container_name: 'mysqlmotors'
    environment:
      MYSQL_DATABASE: 'crawler'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rootteste'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
      - mysql_webmotors_data:/var/lib/mysql

volumes:
  mongodb_webmotors_data:
    external: true
  mysql_webmotors_data:
    external: true